---
- name: "create zk install dir"
  file:
    path: "{{zk_install_dir}}"
    recurse: true
    state: directory
    group: "root"
    owner: "root"
    mode: "777"
  tags:
    - zk


- name: copy zookeeper
  copy:
    src: "zookeeper-{{ zookeeper_version }}.tar.gz"
    dest: /tmp
    owner: "{{zookeeper_user}}"
  tags:
    - zk

- stat:
    path: "/tmp/zookeeper-{{ zookeeper_version }}.tar.gz"
  register: zookeeper_tar_file
  tags:
    - zk
    
- name: "Download ZooKeeper"
  become: true
  become_user: "{{zookeeper_user}}"
  get_url:
    dest: "/tmp/zookeeper-{{ zookeeper_version }}.tar.gz"
    url: "http://mirrors.tuna.tsinghua.edu.cn/apache/zookeeper/zookeeper-{{ zookeeper_version }}/zookeeper-{{ zookeeper_version }}.tar.gz"
    owner: "{{ zookeeper_user }}"
  when: zookeeper_tar_file.stat.exists == False
  tags:
    - zk

- name: "Unpack Zookeeper"
  unarchive:
    copy: false
    dest: "{{zk_install_dir}}"
    src: "/tmp/zookeeper-{{ zookeeper_version }}.tar.gz"
  tags:
    - zk

- name: "link zookeeper-{{zookeeper_version}} to {{ZK_HOME}}"
  file:
    src: "{{zk_install_dir}}/zookeeper-{{zookeeper_version}}"
    dest: "{{ZK_HOME}}"
    state: link
    owner: "{{zookeeper_user}}"
    group: "{{zookeeper_group}}"


- name: "Create Zookeeper directories"
  become: true
  file:
    group: "{{ zookeeper_group }}"
    owner: "{{ zookeeper_user }}"
    path: "{{ item }}"
    recurse: true
    state: directory
    mode: "u=rwx,og=r"
  with_items:
    - "{{zookeeper_bin_dir}}"
    - "{{ zookeeper_data_dir }}"
    - "{{ zookeeper_log_dir }}"
    - "{{ zookeeper_tmp_dir }}"
    - "{{ zookeeper_conf_dir }}"
  tags:
    - zk

- name: "Create the Zookeeper systemd environment file"
  template: src="environment.j2" dest="{{ zookeeper_conf_dir }}/environment" owner={{ zookeeper_user }} group={{ zookeeper_group }} mode=0644
  tags:
    - zk

- name: "Create the Zookeeper systemd service file"
  tags:
    - zk
  template: src="zookeeper.service.j2" dest=/etc/systemd/system/zookeeper.service owner=root group=root mode="ugo=rx"
