---
- hosts: all
  become: yes
  vars_files:
    - "vars/{{env}}.yml"
  roles:
    - common
    - {role: "firewall-ansible"}

- include: redis-playbook.yml
- include: zookeeper-playbook.yml
- include: zabbix-playbook.yml
