---

- hosts: i4
  become: true
  vars_files:
    - "vars/{{env}}.yml"
  roles:
    - common
    - jdk8
    - {"role": "openresty"}
    - {"role": "kibana-openresty-conf"}
    - {"role": "firewall-ansible", "firewall_allowed_tcp_ports":["22", "80"]}
    - {"role": "kibana-ansible"}
    # - {"role": logstash-ansible  }

- hosts: i2
  become: true
  vars_files:
    - "vars/{{env}}.yml"
  roles:
    - common
    - jdk8
    - { "role": "elasticsearch-ansible"}
    - {"role": "firewall-ansible", "firewall_allowed_tcp_ports":["22", "9200", "9300"]}


- hosts: i3
  become: true
  vars_files:
    - "vars/{{env}}.yml"
  roles:
    - common
    - jdk8
    - { "role": "elasticsearch-ansible"}
    - {"role": "firewall-ansible", "firewall_allowed_tcp_ports":["22", "9200", "9300"]}



- hosts: i4
  become: true
  vars_files:
    - "vars/{{env}}.yml"
  roles:
    - common
    - jdk8
    - { "role": "elasticsearch-ansible"}
    - {"role": "firewall-ansible", "firewall_allowed_tcp_ports":["22", "9200", "9300"]}
