---
- hosts: redis-master
  become: yes
  vars_files:
    - "./vars/{{ env }}.yml"
  vars:
    redis_bind: "{{redis_master_bind_ip}}"
  roles:
    - common
    - {role: "firewall-ansible", firewall_allowed_tcp_ports: ["22", "{{redis_port}}"] }
    - redis-ansible

- hosts: redis-slave
  become: yes
  vars_files:
    - "vars/{{ env }}.yml"
  vars:
      redis_slaveof: "{{redis_master_bind_ip}} {{redis_master_bind_port}}"
  roles:
    - common
    - {role: "firewall-ansible", firewall_allowed_tcp_ports: ["22", "{{redis_port}}"] }
    - redis-ansible
