---
zabbixserver_packages:
  - build-essential
  - gcc
  - curl
  - wget
  - libmysqld-dev # required by zabbix server with mysql
  - libsnmp-dev
  - libcurl4-gnutls-dev
  - libxml2-dev
  - unixodbc-dev
  - libssh-dev
  - libssh2-1-dev
  - fping
  - snmp
  - python-psycopg2
  - libpq-dev
  - snmp-mibs-downloader
