---
# defaults file for php7
# PHP-FPM configuration.
php_enable_php_fpm: true
php_fpm_listen: "127.0.0.1:9000"
php_fpm_listen_allowed_clients: "127.0.0.1"
php_fpm_pm_max_children: 50
php_fpm_pm_start_servers: 5
php_fpm_pm_min_spare_servers: 5
php_fpm_pm_max_spare_servers: 5
php_fpm_daemon: php-fpm
php_webserver_daemon: "nginx"

php_conf_paths:
  - /etc

php_extension_conf_paths:
  - /etc/php.d

php_apc_conf_filename: 50-apc.ini
php_opcache_conf_filename: 10-opcache.ini
php_fpm_daemon: php-fpm
php_fpm_conf_path: "/etc/fpm"
php_fpm_pool_conf_path: "/etc/php-fpm.d/www.conf"

php_fpm_pool_user: php_fpm
php_fpm_pool_group: php_fpm
