---
- name: preinstall | install dependces rpm
  yum: name={{ item }} state=present
  with_items:
      - unzip
      - gcc
      - glibc

- name: preinstall | add redis user
  user:
    name: "{{redis_user}}"
    state: present
    createhome: no
    comment: "redis user"
    system: yes
    shell: /sbin/nologin

- name: preinstall | config limit
  lineinfile:
    dest: /etc/security/limits.conf
    line: "{{ redis_user }}    -       nproc           65535"

- stat:
    path: "{{redis_tar_download_path}}"
  register: redis_tar

- copy:
    src: "{{redis_tar_file_name}}"
    dest: "{{redis_tar_download_path}}"
    owner: "{{redis_user}}"
  ignore_errors: yes


- name: download
  get_url:
    url: "{{redis_tar_download_url}}"
    dest: "{{redis_tar_download_path}}"
    owner: "{{redis_user}}"
  when: redis_tar.stat.exists == False


- name: "preinstall | unarchive {{ redis_tar_download_path }}"
  become: yes
  unarchive:
    src: "{{ redis_tar_download_path }}"
    owner: "{{redis_user}}"
    remote_src: True
    dest: /opt
