---

- name: remove | sending sigterm to any running redis processes
  shell: pkill -u {{redis_user}} || true

- name: remove | rm /opt/redis
  file: path={{ item }} state=directory state=absent
  with_items:
      - "{{ redis_install_dir }}"
      - "/opt/redis-{{redis_version}}"
      - "/etc/redis"

- name: remove| rm -rf /etc/init.d/redis redis-sentinel
  file: path=/etc/init.d/{{ item }} state=absent
  with_items:
      - redis-server
      - redis-sentinel

  #- name: remove| reboot server
  #shell: reboot
