---

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_os_family != "RedHat"
  tags:
    - zabbix3
- name: Include OS-specific variables (RedHat).
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
  when: ansible_os_family == "RedHat"
  tags:
    - zabbix3
- include: centos7.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
