---
# tasks file for syslog-ng-ansible
# - name: install syslog-ng
#   yum:
#     name: syslog-ng
#     state: present


- name: Install Syslog-ng
  yum:
    name: syslog-ng
    state: present

- name: Configure Syslog-ng
  template:
    backup: yes
    src: syslog-ng.conf.j2
    dest: /etc/syslog-ng/conf.d/syslog-ng.conf
    mode: 0644
    owner: root
    group: wheel
  notify: Enable syslog-ng
