---

- group: name="{{kafka_group}}" system=yes
  tags:
    - kafka

- user: name="{{kafka_user}}" group={{kafka_group}} system=yes
  tags:
    - kafka

- name: Install kafka
  include: build.yml
  tags:
    - kafka

- name: Install kafka
  include: configure.yml
  tags:
    - kafka
